# Generated by Django 4.1 on 2023-06-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='external',
            name='created_at',
        ),
    ]
