# Generated by Django 4.1 on 2023-06-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='rated_user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='custom_user',
            new_name='rater',
        ),
    ]
