# Generated by Django 4.1 on 2023-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, choices=[('bcis', 'Bachelor of Computer Information System'), ('bit', 'Bachelor of Tourism'), ('bba', 'Bachelor of Business Administration'), ('bba-bi', 'Bachelor of Business Administration BI')], max_length=255, null=True),
        ),
    ]
