# Generated by Django 4.1 on 2023-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
