# Generated by Django 4.1 on 2023-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='enrollment_date',
        ),
    ]
