# Generated by Django 4.1 on 2023-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
