# Generated by Django 4.1 on 2023-06-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashop', '0005_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ashop.orderitem'),
        ),
    ]
