# Generated by Django 4.1 on 2023-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashop', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_bills'),
        ),
    ]
