# Generated by Django 4.1 on 2023-06-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashop', '0008_payment_proof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
