# Generated by Django 4.1 on 2023-07-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashop', '0014_alter_featuredproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
