# Generated by Django 4.1 on 2023-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashop', '0015_product_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
