# Generated by Django 4.1 on 2023-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='acs', max_length=255),
        ),
    ]
