# Generated by Django 4.1 on 2023-06-09 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('user', 'job')},
        ),
    ]
