# Generated by Django 4.1 on 2023-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_alter_jobpost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
