# Generated by Django 4.1 on 2023-06-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_remove_jobpost_company_jobpost_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company_name',
            new_name='company',
        ),
    ]
