# Generated by Django 4.1 on 2023-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0004_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='vote_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
