# Generated by Django 4.1 on 2023-06-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0004_alter_jobpost_expire_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
    ]
