# Generated by Django 4.1 on 2023-06-08 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acs', '0005_jobpost_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='vote_count',
        ),
        migrations.CreateModel(
            name='JobVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acs.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
