# Generated by Django 4.1 on 2023-06-08 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acs', '0006_remove_jobpost_vote_count_jobvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobvote',
            unique_together={('jobpost', 'user')},
        ),
    ]
