# Generated by Django 4.1 on 2023-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0006_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
