# Generated by Django 4.1 on 2023-07-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0007_jobpost_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
